### ISSUE TITLE
DEM U8 - Antrag der Schachjugend in Berlin JV 2020

### ISSUE THREAD

**Issue by lquante** [Schachjugend/Spielordnung#70]
Ab dem Jahr 2022 findet parallel zur Deutschen Jugendeinzelmeisterschaft (DEM) U10 bis U18 eine DEM U8/U8w statt.
Die Jugendturnierordnung möge in §1.3 ergänzt werden durch:
...
Deutsche Einzelmeisterschaften für Jugendliche unter 8 Jahren (DEM U8),
Deutsche Einzelmeisterschaften für weibliche Jugendliche unter 8 Jahren (DEM U8w),
Der AK Spielbetrieb möge alle weiteren Abschnitte der JTO entsprechend anpassen.

**Comment by lquante** [comment]
Der Antragssteller hat seinen Antrag auf der JV 2020 in Freiburg dahingehend geändert, dass keine getrennte DEM U8w eingerichtet werden soll.

**Comment by lquante** [comment]
Begründung:
In der Altersklasse U8 gibt es immer mehr Spieler. U8-Turniere wie u.a. Sebnitz er- freuen sich seit Jahren hoher Anmeldezahlen. Auch eine Welt- und Europameisterschaft gibt es inzwischen, für die Deutschland kein geeignetes Auswahlturnier hat, da nicht alle U8-Spieler an der DEM U10 teilnehmen. Durch die Einführung einer DEM U8/U8w hätte die Deutsche Schachjugend ein Auswahlturnier für die EM und WM U8 und könnten frühzeitiger Talente entdecken und fördern. Dem weltweiten Trend auch in der AK U8 angemessene Turniere anzubieten, würde damit Rechnung getragen. Damit die Landesverbände genügend Vorlauf für einen Qualifikationszyklus haben, wird die Einführung einer DEM U8 und U8w erst für 2022 beantragt.
Diese soll zur selben Zeit und am selben Ort wie die anderen zentral ausgerichteten DEMs ausgerichtet werden. Dabei betrachten wir den Modus, wie er derzeit in der U10 genutzt wird, für die jungen Spieler der U8 als noch zu anstrengend. Der AK Spielbetrieb wird gebeten in Zusammenarbeit mit geeigneten U8-erfahrenen Trainern einen angemessenen Modus zu erarbeiten. Dabei sollen mindestens 7 Runden an mindes- tens 5 Tagen gespielt werden. Die Bedenkzeit soll mind. 60 min plus 15 min betragen. Auch für die Kontingentberechnung wird der AK Spielbetrieb gebeten eine Übergangs- lösung für die ersten drei Jahre zu erarbeiten. Danach soll die Berechnung der DEM U10 übernommen werden.
Die Antragsteller bieten an den AK Spielbetrieb bei der Erarbeitung der genannten Maßnahmen (Übergangslösung der Kontingentberechnung, Modus) zu unterstützen.

**Comment by lquante** [comment]
Da der Antrag nicht den Erfordernissen der Jugendordnung 6.6, Satz 3 "Anträge, die Ordnungsänderungen zum Ziel haben, sind nur zulässig, wenn daraus der beantragte neue Wortlaut des Ordnungstextes eindeutig hervorgeht." genügte, hat der Bundesrechtsberater darauf hingewiesen, dass der gesamte Antrag keine Änderungen der Spielordnung bewirken kann, sondern nur einen Arbeitsauftrag an den Arbeitskreis Spielbetrieb darstellt, entsprechende ordnungsändernde Anträge zur Jugendversammlung 2021 vorzubereiten.

**Comment by lquante** [comment]
Da der Antrag nicht den Erfordernissen der Jugendordnung 6.6, Satz 3 "Anträge, die Ordnungsänderungen zum Ziel haben, sind nur zulässig, wenn daraus der beantragte neue Wortlaut des Ordnungstextes eindeutig hervorgeht." genügte, hat der Bundesrechtsberater darauf hingewiesen, dass der gesamte Antrag keine Änderungen der Spielordnung bewirken kann, sondern nur einen Arbeitsauftrag an den Arbeitskreis Spielbetrieb darstellt, entsprechende ordnungsändernde Anträge zur Jugendversammlung 2021 vorzubereiten.

**Comment by lquante** [comment]
Der Arbeitsauftrag wurde auf der Jugendversammlung 2020 in Freiburg bei 132 Ja Stimmen und 118 Gegenstimmen erteilt.

**Comment by lquante** [comment]
Der Arbeitskreis Spielbetrieb wird den Landesschachjugenden (LSJ) zur gegebenen Zeit einen Diskussionsvorschlag für mögliche Rahmenbedingungen einer DEM U8 vorlegen, um die  Einbindung der LSJ beim Entwurf der ordnungsändernen Anträgen sicherzustellen.

**Comment by fnogatz** [comment]
Die DEM U8 findet sich unterdessen offenbar höchstoffiziell in der JSpO. Kann dieses Issue also geschlossen werden?
